config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get '/', to: 'events#index'
  resources :attendances
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	#Permet d'envoyer un email à l'utilisateur juste après la création de son compte
	after_create :welcome_send

	has_many :attendances
	has_many :events, through: :attendances
	has_many :created_events,  foreign_key: 'admin_id', class_name: "Event"

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show]
  before_action :only_your_profile_page, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :encrypted_password, :description, :first_name, :last_name)
    end

    #Methode permettant de restreindre l'accès à un utilisateur uniquement à sa page de profil
    def only_your_profile_page
      @user = User.find(params[:id])
    
      if current_user != @user
        redirect_to events_path, notice: "Access denied! You can only view your own profile page."
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :encrypted_password %>
    <%= form.text_field :encrypted_password %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>

<div class="jumbotron jumbotron-fluid" style="background-color:#cae3ed">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <!-- Ajout de la fonctionnalité qui permet d'ajouter une alerte au user-->
  <% if flash[:alert] != nil %>
    <div class='alert alert-success mt-4'>
      <%= flash[:alert] %>
    </div>
    <% end %>

    <h1 class="display-5 text-center" style="color:#37444a" >🧑🏼 BIENVENUE à toi!!!! 👨🏻</h1><br>
    <p class="text-center"> Tu trouveras ci-dessous la liste de tous les Users que nous avons en base à ce jour <br><br>
    </p>
  </div>
  </div>

</div>

<h1 class="display-5 text-center" style="color:#37444a">List des Users</h1><br>
<p id="notice"><%= notice %></p>
<% @users.each do |user| %>
  <div class="card-deck" style="margin-left: 15px; margin-right: 15px">
  <div class="card" style="width: 18rem; background-color:#cae3ed">
    <div class="card-body text-center">
      <h5 class="card-title"><%=link_to "#{user.first_name} #{user.last_name}", user_path(user.id)%></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%=user.description%></h6>

      <a href=><button class='btn btn-outline-primary' ><%= link_to 'Show', user %></button></a>
    </div>
    </div>
  </div>
<br/>
<% end %>
</html>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
      <div class="jumbotron jumbotron-fluid" style="background-color:#cae3ed">
        <div class="container">
          <p id="notice"><%= notice %></p>
          <h1 class="display-5 text-center" style="color:#37444a" ><%= @user.first_name %> <%= @user.last_name %> </h1><br>
          <p class="text-center">
        
        <strong>Email: </strong><%= @user.email %><br><br>

        <strong>Description: </strong><%= @user.description %><br><br>

        <a href=><button class='btn btn-outline-primary' ><%= link_to 'Edit', edit_user_registration_path %></button></a>
        <a href=><button class='btn btn-success' ><%= link_to 'Back', users_path %></button></a>
          </p>
          </div>
          <br/><br/><br/>
      </div>

<h3 class="display-5 text-center" style="color:#37444a ">Voici la liste des Events postés par <%= @user.first_name %></h3><br>
<% @user.events.each do |event| %>
<div class="list-group" style="margin-left: 15px; margin-right: 15px" >
   <a href="<%= event_path(event.id)%>" class="list-group-item list-group-item-action " style="background-color:#cae3ed">
        <div class="d-flex w-100 justify-content-between">

            <h5 class="mb-1"><%= event.title %></h5>
            <small>Event n°<%= event.id %></small>
        </div>
          <p class="mb-1"><%=event.description%></p>
          <small><%= event.attendances.count %> attendees</small>
    </a>   
</div>

  
<br/>
<% end %>




</html>