config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get '/', to: 'events#index'
  resources :attendances
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS: Ajout des fichier CDN liés à Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <header>
   <!-- Ajout d'une NavBar bootstrap-->
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to 'Eventbrite Project', events_path, class: "navbar-brand" %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
          <%= link_to 'Home', events_path, class: "nav-link btn mr-1"  %>
          </li>
          <li class="nav-item">
          <%= link_to 'New Event', new_event_path, class: "nav-link btn mr-1"  %> 
          </li>
       

        <ul class="navbar-nav my-2 my-lg-0" style="position: absolute; left: 80%;">
        <% if !current_user%> 

          <li class="nav-item">
          <%=link_to 'SignIn', new_user_session_path, class: "btn btn-outline-primary mr-2" %>
          </li>
          <%= link_to 'SignUp',new_user_registration_path, class: "btn btn-outline-primary" %>
          </li>
          <% else %>
          <li class="nav-item ">
          <%= link_to 'My Profile',user_path(current_user.id), class: "nav-link btn mr-1" %>
          </li>
          <li class="nav-item ">
          <%= link_to 'SignOut',destroy_user_session_path, method: :delete, data: {confirm: 'Êtes-vous sûr de vous déconnecter ?'}, class: "nav-link btn btn-outline-danger" %> 
          </li>
          <% end %>
        </ul>

          
      </div>

    </nav>
  </header>

  <body>
    <%= yield %>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
  </body>
</html>